//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookizi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int Id { get; set; }
        public string TenFood { get; set; }
        public string NguyenLieu { get; set; }
        public Nullable<int> Calories { get; set; }
        public string Congthucnauan { get; set; }
        public string Hinhanh { get; set; }
    }
}
