<?xml version="1.0" encoding="utf-8"?><Database Name="FoodDB" Class="MydataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\FoodDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FoodDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Food" Member="Foods">
    <Type Name="Food">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenFood" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NguyenLieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>